#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v13
# autospec commit: 2659038
#
%define keepstatic 1
Name     : pixman
Version  : 0.43.4
Release  : 59
URL      : https://cairographics.org/releases/pixman-0.43.4.tar.gz
Source0  : https://cairographics.org/releases/pixman-0.43.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: pixman-lib = %{version}-%{release}
Requires: pixman-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glib-dev
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libpng-dev32
BuildRequires : pkgconfig(32glib-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : zlib-dev32
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Pixman
======
Pixman is a library that provides low-level pixel manipulation
features such as image compositing and trapezoid rasterization.

%package dev
Summary: dev components for the pixman package.
Group: Development
Requires: pixman-lib = %{version}-%{release}
Provides: pixman-devel = %{version}-%{release}
Requires: pixman = %{version}-%{release}

%description dev
dev components for the pixman package.


%package dev32
Summary: dev32 components for the pixman package.
Group: Default
Requires: pixman-lib32 = %{version}-%{release}
Requires: pixman-dev = %{version}-%{release}

%description dev32
dev32 components for the pixman package.


%package lib
Summary: lib components for the pixman package.
Group: Libraries
Requires: pixman-license = %{version}-%{release}

%description lib
lib components for the pixman package.


%package lib32
Summary: lib32 components for the pixman package.
Group: Default
Requires: pixman-license = %{version}-%{release}

%description lib32
lib32 components for the pixman package.


%package license
Summary: license components for the pixman package.
Group: Default

%description license
license components for the pixman package.


%prep
%setup -q -n pixman-0.43.4
cd %{_builddir}/pixman-0.43.4
pushd ..
cp -a pixman-0.43.4 build32
popd
pushd ..
cp -a pixman-0.43.4 buildavx2
popd
pushd ..
cp -a pixman-0.43.4 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720103413
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FCFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CXXFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export LDFLAGS_GENERATE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CFLAGS_USE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FCFLAGS_USE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FFLAGS_USE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export CXXFLAGS_USE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export LDFLAGS_USE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dmmx=disabled \
-Dsse2=enabled \
-Dssse3=enabled \
-Dgtk=disabled  builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS_GENERATE -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS_GENERATE -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS_GENERATE -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dmmx=disabled \
-Dsse2=enabled \
-Dssse3=enabled \
-Dgtk=disabled  builddiravx2
ninja -v -C builddiravx2
pushd builddiravx2
make check || :
popd
rm -rf builddiravx2
CFLAGS="$CFLAGS_USE -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS_USE -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS_USE -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dmmx=disabled \
-Dsse2=enabled \
-Dssse3=enabled \
-Dgtk=disabled  builddiravx2
ninja -v -C builddiravx2
GOAMD64=v4
CFLAGS="$CFLAGS_GENERATE -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 " CXXFLAGS="$CXXFLAGS_GENERATE -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 " LDFLAGS="$LDFLAGS_GENERATE -march=x86-64-v4 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dmmx=disabled \
-Dsse2=enabled \
-Dssse3=enabled \
-Dgtk=disabled  builddiravx512
ninja -v -C builddiravx512
pushd builddiravx512
make check || :
popd
rm -rf builddiravx512
CFLAGS="$CFLAGS_USE -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 " CXXFLAGS="$CXXFLAGS_USE -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 " LDFLAGS="$LDFLAGS_USE -march=x86-64-v4 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dmmx=disabled \
-Dsse2=enabled \
-Dssse3=enabled \
-Dgtk=disabled  builddiravx512
ninja -v -C builddiravx512
pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
meson --libdir=lib32 --prefix=/usr --buildtype=plain -Dmmx=disabled \
-Dsse2=enabled \
-Dssse3=enabled \
-Dgtk=disabled -Ddemos=disabled builddir
ninja -v -C builddir
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FCFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export FFLAGS_GENERATE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CXXFLAGS_GENERATE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export LDFLAGS_GENERATE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
export CFLAGS_USE="$CLEAR_INTERMEDIATE_CFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FCFLAGS_USE="$CLEAR_INTERMEDIATE_FCFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export FFLAGS_USE="$CLEAR_INTERMEDIATE_FFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export CXXFLAGS_USE="$CLEAR_INTERMEDIATE_CXXFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
export LDFLAGS_USE="$CLEAR_INTERMEDIATE_LDFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/pixman
cp %{_builddir}/pixman-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pixman/3b90aaf730fa20460f8fe3fd20c16daf3acaba59 || :
pushd ../build32/
DESTDIR=%{buildroot} ninja -C builddir install
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v4
DESTDIR=%{buildroot}-v4 ninja -C builddiravx512 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pixman-1/pixman-version.h
/usr/include/pixman-1/pixman.h
/usr/lib64/libpixman-1.so
/usr/lib64/pkgconfig/pixman-1.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libpixman-1.so
/usr/lib32/pkgconfig/32pixman-1.pc
/usr/lib32/pkgconfig/pixman-1.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libpixman-1.so.0.43.4
/V4/usr/lib64/libpixman-1.so.0.43.4
/usr/lib64/libpixman-1.so.0
/usr/lib64/libpixman-1.so.0.43.4

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libpixman-1.so.0
/usr/lib32/libpixman-1.so.0.43.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pixman/3b90aaf730fa20460f8fe3fd20c16daf3acaba59
